/**
 * Created by K.Sachko on 30.10.2017.
 */

export default [
  {
    id: 'boby',
    name: 'Sponge Bob',
    avatar: 'src/images/mini/back_bob_mini.png',
    back: 'src/images/sponge_bob/back_bob.png',
    faces: [
      'src/images/sponge_bob/bob_1.png',
      'src/images/sponge_bob/bob_2.png',
      'src/images/sponge_bob/bob_3.png',
      'src/images/sponge_bob/gery_1.png',
      'src/images/sponge_bob/krabs_1.png',
      'src/images/sponge_bob/krabs_2.png',
      'src/images/sponge_bob/patrick_1.png',
      'src/images/sponge_bob/patrick_2.png',
      'src/images/sponge_bob/pearl_1.png',
      'src/images/sponge_bob/plankton_1.png',
      'src/images/sponge_bob/squidward_2.png',
      'src/images/sponge_bob/squidward_3.png',
    ],
  },
  {
    id: 'hahariki',
    name: 'Smeshariki',
    avatar: 'src/images/mini/smeshariki_back_mini.png',
    back: 'src/images/smeshariki/smeshariki_back.png',
    faces: [
      'src/images/smeshariki/1.png',
      'src/images/smeshariki/2.png',
      'src/images/smeshariki/3.png',
      'src/images/smeshariki/4.png',
      'src/images/smeshariki/5.png',
      'src/images/smeshariki/6.png',
      'src/images/smeshariki/7.png',
      'src/images/smeshariki/8.png',
      'src/images/smeshariki/9.png',
      'src/images/smeshariki/10.png',
      'src/images/smeshariki/11.png',
      'src/images/smeshariki/12.png',
    ],
  },
  {
    id: 'south_park',
    name: 'South Park',
    avatar: 'src/images/mini/Park_back_mini.png',
    back: 'src/images/south_park/back.png',
    faces: [
      'src/images/south_park/cartman_1.png',
      'src/images/south_park/cartman_2.png',
      'src/images/south_park/cartman_3.png',
      'src/images/south_park/kenny_1.png',
      'src/images/south_park/kenny_2.png',
      'src/images/south_park/kenny_3.png',
      'src/images/south_park/kyle_1.png',
      'src/images/south_park/kyle_2.png',
      'src/images/south_park/kyle_3.png',
      'src/images/south_park/stan_1.png',
      'src/images/south_park/stan_2.png',
      'src/images/south_park/stan_3.png',
    ],
  },
];
